name: hidrotec
description: Pool controller projet.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.2
  firebase_core: ^2.14.0
  provider: ^6.0.5
  firebase_auth: ^4.6.3
  google_fonts: ^5.1.0
  shared_preferences: ^2.2.0
  firebase_database: ^10.2.3
  flutter_circle_color_picker: ^0.3.0
  segment_display: ^0.5.0
  syncfusion_flutter_gauges: ^22.1.37
  brasil_fields: ^1.13.1
  outlined_text: ^1.0.1
  restart_app: ^1.2.1
  intl: ^0.18.1
  http: ^1.1.0
  flutter_blue: ^0.8.0
  lottie: ^2.6.0
  animated_splash_screen: ^1.3.0
  page_transition: ^2.0.9
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:

 
  uses-material-design: true

 
  assets:
    - lib/image/ 

  